pipeline {
     agent any
     stages {
        stage("Build") {
            steps {
                 sh "cd ReactJS/'Javascript Calculator'"
                sh "npm install"
                sh "npm run build"
            }
        }
    }
}
